#### Question: Generating Fashion Products with GAN
#### Dataset Problem: Use the Fashion MNIST dataset to train a GAN for generating new fashion product images. 
#### The Fashion-MNIST dataset is proposed as a more challenging replacement dataset for the
#### MNIST dataset. It is a dataset comprised of 60,000 small square 28 Å~ 28-pixel grayscale images of items of 10 types of clothing, such as shoes, t-shirts, dresses, and more. The mapping of all 0-9 integers to class labels are listed below.
0: T-shirt/top
1: Trouser
2: Pullover
3: Dress
4: Coat
5: Sandal
6: Shirt
7: Sneaker
8: Bag
9: Ankle boot
##### Download data from: https://github.com/zalandoresearch/fashion-mnist


In [4]:
from tensorflow.keras.datasets import fashion_mnist
import numpy as np

# Load Fashion MNIST
(train_images1, _), (_, _) = fashion_mnist.load_data()

# Normalize images to [0, 1] and reshape
train_images2 = train_images1 / 255.0
train_images = np.expand_dims(train_images2, axis=-1) 

In [5]:
train_images1

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
train_images2

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
train_images

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [2]:
def build_generator():
    inputs = tf.keras.layers.Input(shape=(100,))
    x = tf.keras.layers.Dense(7*7*256, use_bias=False)(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.LeakyReLU()(x)
    x = tf.keras.layers.Reshape((7, 7, 256))(x)

    x = tf.keras.layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.LeakyReLU()(x)

    x = tf.keras.layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.LeakyReLU()(x)

    outputs = tf.keras.layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')(x)

    model = tf.keras.Model(inputs, outputs)
    return model


In [3]:
def build_discriminator():
    inputs = tf.keras.layers.Input(shape=(28, 28, 1))
    x = tf.keras.layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same')(inputs)
    x = tf.keras.layers.LeakyReLU()(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    x = tf.keras.layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same')(x)
    x = tf.keras.layers.LeakyReLU()(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    x = tf.keras.layers.Flatten()(x)
    outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

    model = tf.keras.Model(inputs, outputs)
    return model


In [4]:
import tensorflow as tf
cross_entropy = tf.keras.losses.BinaryCrossentropy()

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    return real_loss + fake_loss


In [5]:
generator_optimizer = tf.keras.optimizers.Adam(1e-4)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)

In [6]:
import matplotlib.pyplot as plt
import os

def generate_and_save_images(model, epoch, test_input, output_dir="generated_images"):
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate predictions
    predictions = model(test_input, training=False)
    predictions = (predictions * 127.5 + 127.5).numpy()  # Rescale images to [0, 255]
    
    # Plot and save the images
    fig = plt.figure(figsize=(4, 4))
    for i in range(predictions.shape[0]):
        plt.subplot(4, 4, i + 1)
        plt.imshow(predictions[i, :, :, 0], cmap='gray')
        plt.axis('off')
    
    # Save the figure
    filename = os.path.join(output_dir, f"image_at_epoch_{epoch:04d}.png")
    plt.savefig(filename)
    plt.close(fig)
    print(f"Saved image for epoch {epoch} at {filename}")


In [7]:
import os
import tensorflow as tf

EPOCHS = 50
NOISE_DIM = 100
BATCH_SIZE = 256
num_examples_to_generate = 16

# Seed for consistent image generation
seed = tf.random.normal([num_examples_to_generate, NOISE_DIM])

# Training Step
@tf.function
def train_step(images):
    noise = tf.random.normal([BATCH_SIZE, NOISE_DIM])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)
        
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)
        
        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)
    
    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)
    
    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

# Full Training Loop
def train(dataset, epochs):
    for epoch in range(epochs):
        for image_batch in dataset:
            train_step(image_batch)
        print(f'Epoch {epoch+1}/{epochs} complete')
        generate_and_save_images(generator, epoch + 1, seed)


In [8]:
# Prepare Dataset
train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(60000).batch(BATCH_SIZE)

# Train the GAN
generator = build_generator()
discriminator = build_discriminator()
train(train_dataset, EPOCHS)

Epoch 1/50 complete
Saved image for epoch 1 at generated_images\image_at_epoch_0001.png
Epoch 2/50 complete
Saved image for epoch 2 at generated_images\image_at_epoch_0002.png
Epoch 3/50 complete
Saved image for epoch 3 at generated_images\image_at_epoch_0003.png
Epoch 4/50 complete
Saved image for epoch 4 at generated_images\image_at_epoch_0004.png
Epoch 5/50 complete
Saved image for epoch 5 at generated_images\image_at_epoch_0005.png
Epoch 6/50 complete
Saved image for epoch 6 at generated_images\image_at_epoch_0006.png
Epoch 7/50 complete
Saved image for epoch 7 at generated_images\image_at_epoch_0007.png
Epoch 8/50 complete
Saved image for epoch 8 at generated_images\image_at_epoch_0008.png
Epoch 9/50 complete
Saved image for epoch 9 at generated_images\image_at_epoch_0009.png
Epoch 10/50 complete
Saved image for epoch 10 at generated_images\image_at_epoch_0010.png
Epoch 11/50 complete
Saved image for epoch 11 at generated_images\image_at_epoch_0011.png
Epoch 12/50 complete
Saved i

Generative Adversarial Networks (GANs) are a class of machine learning models designed to generate new data samples that resemble a given dataset. They consist of two neural networks, a Generator and a Discriminator, which are trained together in a competitive process.

Key Components of GANs:
Generator (G):

The Generator creates new data samples.
It starts with random noise (latent space input) and learns to transform it into data that resembles the training dataset.
The Generator's goal is to fool the Discriminator into thinking the generated data is real.
Discriminator (D):

The Discriminator is a binary classifier.
It takes both real data (from the dataset) and fake data (from the Generator) as input and attempts to classify them as real or fake.
The Discriminator’s goal is to correctly distinguish between real and fake data.

How GANs Work:
The Generator creates a sample from random noise.
The Discriminator evaluates this sample along with real samples.
Both networks are updated:
The Generator is updated to produce better "fakes."
The Discriminator is updated to better distinguish real from fake samples.
This process continues until the Generator produces samples so realistic that the Discriminator can no longer reliably distinguish between real and fake.

Understanding the Losses:
Generator Loss: Indicates how well the generator is fooling the discriminator.
Ideally, this should gradually decrease, showing that the generator is improving over time.
Discriminator Loss: Indicates how well the discriminator distinguishes between real and generated data.
This should ideally stay around 0.5 (indicating it cannot confidently distinguish between real and fake).
If one model's loss dominates (e.g., discriminator loss close to 0, generator loss increasing sharply), training may be imbalanced.